package ccxtpro
import (
    "strings"
    ccxt "github.com/KyleOlhausen/go-ccxt/goccxt"
)

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

type IExchange interface {
    ccxt.IExchange
}

func CreateExchange(exchangeId string, options map[string]interface{}) ccxt.IExchange {
    exchangeId = strings.ToLower(exchangeId)
    switch exchangeId {
    case "binance":
        itf := NewBinance(options)
        return itf
    case "deribit":
        itf := NewDeribit(options)
        return itf
    case "hyperliquid":
        itf := NewHyperliquid(options)
        return itf
    case "aster":
        itf := NewAster(options)
        return itf
    default:
        return nil
    }
}
