package ccxt
// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code



func DynamicallyCreateInstance(exchangeId string, exchangeArgs map[string]interface{}) (ICoreExchange, bool) {
    switch exchangeId {

    case "Exchange":
        ExchangeItf := &Exchange{}
        ExchangeItf.Init(exchangeArgs)
        return ExchangeItf, true

    case "binance":
        binanceItf := NewBinanceCore()
        binanceItf.Init(exchangeArgs)
        return binanceItf, true
    case "deribit":
        deribitItf := NewDeribitCore()
        deribitItf.Init(exchangeArgs)
        return deribitItf, true
    case "hyperliquid":
        hyperliquidItf := NewHyperliquidCore()
        hyperliquidItf.Init(exchangeArgs)
        return hyperliquidItf, true
    case "aster":
        asterItf := NewAsterCore()
        asterItf.Init(exchangeArgs)
        return asterItf, true
    default:
        return nil, false
    }
}
